### ISSUE TITLE
IndexError: list index out of range`

### ISSUE THREAD

**Issue by fungalstat** [saharmor/dalle-playground#10]
Hello! Help me with this error please

`
[34m[1mwandb[39m[22m: Downloading large artifact wzoooa1c:latest, 1672.79MB. 7 files... Done. 0:0:0
Downloading: 100%|██████████████████████████████████████████████████████████████████████| 434/434 [00:00<00:00, 130kB/s]

Downloading: 100%|███████████████████████████████████████████████████████████████████| 290M/290M [00:25<00:00, 11.8MB/s]

[34m[1mwandb[39m[22m: Downloading large artifact wzoooa1c:latest, 1672.79MB. 7 files... Done. 0:0:0

Downloading: 100%|█████████████████████████████████████████████████████████████████| 33.8M/33.8M [00:02<00:00, 11.9MB/s]
  0%|          | 0/1 [00:00<?, ?it/s]
--> DALL-E Server is up and running!
Traceback (most recent call last):
  File "app.py", line 152, in <module>
    app.run(host="0.0.0.0", port=int(sys.argv[1]), debug=False)
IndexError: list index out of range`

**Comment by Nico2018** [comment]
Run `python app.py 8080` instead just `python app.py`
README needs an update.

**Comment by fungalstat** [comment]
> Run `python app.py 8080` instead just `python app.py` README needs an update.

As a result, I started by fixing the port in the file app.py at 8000, but with a post request to my ip, it does not give out a picture

**Comment by fungalstat** [comment]
But the terminal says that the picture is given and the post request gives an error timeout

**Comment by Nico2018** [comment]
(The generation takes a long time)
Could you post the log of terminal error?

**Comment by fungalstat** [comment]
> (The generation takes a long time) Could you post the log of terminal error?

Yes, but I made a big timeout for the request, the terminal writes that the request was successfully completed (200), but the request itself does not come

**Comment by Nico2018** [comment]
Can you describe the steps to replicate?
Maybe some package is missing, or you are not using the /interface to generate the images?

**Comment by fungalstat** [comment]
I'm not using interface, I make 

```
url = 'http://myip:8000/dalle'
myobj = {"text": text, "num_images": 1}
file = await requests.post(url, json=myobj, headers=HEADERS, timeout=1000)
```

After 700 seconds in terminal I see code 200, but request is timeout after 1000 seconds

**Comment by Nico2018** [comment]
Ok, I'll try to do the same, but if you can try to use the frontend as well, to make sure the backend doesn't work.

**Comment by saharmor** [comment]
@fungalstat closing the issue for now. Feel free to reopen after using the frontend to isolate the possible issue and by stating the steps to reproduce.
