### ISSUE TITLE
Path Error on Windows

### ISSUE THREAD

**Issue by KyuubiYoru** [saharmor/dalle-playground#107]
app.py line 39 creates a folder name with ':' in it, that*s an invalid char for an Windows folder name.

**Comment by VeXHarbinger** [comment]
https://github.com/saharmor/dalle-playground/pull/108

**Comment by saharmor** [comment]
Should be solved as part of https://github.com/saharmor/dalle-playground/commit/a64d0597dfae6aeefb504e8f95a5a6e80ba2f161
