### ISSUE TITLE
cloudflared unknown?

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [saharmor/dalle-playground#109]
![Screenshot from 2022-07-11 09-30-09](https://user-images.githubusercontent.com/48828036/178195185-a0bc6466-45a6-44e7-80aa-47ab99ad7a18.png)

**Comment by omerien** [comment]
Try to launch the project in command line with the version of Python you used to install the dependancies and tell us if it works.

**Comment by ThisIsACoolBoy** [comment]
Nope, it doesn’t seem to work for me.

**Comment by omerien** [comment]
Sorry, thought it would resolve your problem

**Comment by saharmor** [comment]
@ThisIsACoolBoy Is this Google Colab? Did you change anything in the notebook before running it? Seems like an environment issue based on this line
`python3: can't open file 'dall-eplayground/backend/app.py': [Errno 2] No such file or directory`

**Comment by ThisIsACoolBoy** [comment]
> @ThisIsACoolBoy Is this Google Colab? Did you change anything in the notebook before running it? Seems like an environment issue based on this line `python3: can't open file 'dall-eplayground/backend/app.py': [Errno 2] No such file or directory`

It appears so in the screenshot, plus I only asked it to change the Dall - E type
