### ISSUE TITLE
ImportError: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by palexpereira** [saharmor/dalle-playground#11]
After following the instructions and running app.py in the backend folder I get this error message:

Traceback (most recent call last):
  File "/home/griffisu/AI/dalle-playground/backend/app.py", line 16, in <module>
    from flask import Flask, request, jsonify
  File "/home/griffisu/AI/dalle-playground/backend/dalleplay/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/griffisu/AI/dalle-playground/backend/dalleplay/lib/python3.9/site-packages/jinja2/__init__.py)

Running Ubuntu with a 3090RTX
Driver version 510.60.02
CUDA version 11.6 
if that helps.

Any ideas? Thanks!

**Comment by Nico2018** [comment]
Did you installed requirements.txt? i also had to change the requirements.txt Flask version like this: `Flask==2.1.0`
once i change that i ran again the pip install of requirements.txt

**Comment by saharmor** [comment]
@palexpereira have you tried what @Nico2018 suggested? This should resolve your issue.

**Comment by palexpereira** [comment]
Hello, I'm sorry for the late reply. I ended up installing it through docker and everything went smooth. Thank you!
