### ISSUE TITLE
Invalid syntax in app.py line 39

### ISSUE THREAD

**Issue by DayMD** [saharmor/dalle-playground#113]
I am trying to run Dall-e on linux mint but when running app.py I get an error on line 39, this line seems to refer to creating logs for the input promps.
![Untitled](https://user-images.githubusercontent.com/18167402/179395155-87ce3677-8c04-4afb-aa41-e9c965719985.png)

**Comment by omerien** [comment]
Similar to #107. Try the fix #108 and tell us if it works.

**Comment by saharmor** [comment]
Should be solved as part of https://github.com/saharmor/dalle-playground/commit/a64d0597dfae6aeefb504e8f95a5a6e80ba2f161
