### ISSUE TITLE
Local development with Docker-compose doesn't work?

### ISSUE THREAD

**Issue by Saman-Izadi** [saharmor/dalle-playground#119]
![image](https://user-images.githubusercontent.com/85870077/183304614-489800fc-ed82-4bc9-9c20-559639a430e1.png)
<img width="963" alt="image" src="https://user-images.githubusercontent.com/85870077/183304796-627e1db4-4b58-48fd-81b1-5ebd436d841c.png">

Uhhhh idk I got the docker app and NVIDIA Container Toolkit on windows with wsl and this happens

**Comment by VeXHarbinger** [comment]
I ran it with mini and mega and both modes worked for me with the current build.  I think I had to "sudo apt update && sudo apt upgrade -y" to get all the components in the Linux env to update though
