### ISSUE TITLE
app.py hangs/freezes

### ISSUE THREAD

**Issue by ansorre** [saharmor/dalle-playground#13]
When trying to run on my local Ubuntu following the "Local development" steps app.py hangs when running 
python app.py 8080
these are the last few lines printed on the console, then nothing happens even waiting some hours.

wandb: WARNING Do NOT share these links with anyone. They can be used to claim your runs.
wandb: Downloading large artifact mega-1:latest, 9873.84MB. 7 files... Done. 0:0:0
wandb: Downloading large artifact mega-1:latest, 9873.84MB. 7 files... Done. 0:0:0
  0%|          | 0/1 [00:00<?, ?it/s]

Not only. The line "your url is: https........." which is printed in the jupiter collab when running app.py never gets printed out when running local.
Any help?

**Comment by saharmor** [comment]
@ansorre seems like you're trying to use[DALL-E Mega](https://github.com/saharmor/dalle-playground/issues/10? If so, it takes time to load based on the machine you use

**Comment by Matheus-Garbelini** [comment]
@saharmor In my case, it's not downloading. I get 0:0:0 all the time and I've checked network activity to confirm that no download is taking place. Is there some way to modify the backend app so we can refer to a locally stored model?
Particularly, how can we modify this line: https://github.com/saharmor/dalle-playground/blob/main/backend/app.py#L65
to the local folder

**Comment by saharmor** [comment]
Closing the issue due to no response. Feel free to reopen if this is still relevant.
