### ISSUE TITLE
_run_cloudflared() missing required positional argument: 'metrics_port'

### ISSUE THREAD

**Issue by chemaomao** [saharmor/dalle-playground#131]
Running into an error with generating a Cloudflare URL on Google Colab.

> Exception in thread Thread-12:
> Traceback (most recent call last):
>   File "<ipython-input-2-9429ef87b311>", line 14, in start_cloudflared
> TypeError: _run_cloudflared() missing 1 required positional argument: 'metrics_port'

It was running great on Google Colab two weeks ago on both free/public & paid colab account.
Server still starts, but no front end access without the Cloudflare backend url. 

<img width="1295" alt="Screenshot 2023-02-15 at 13 34 01" src="https://user-images.githubusercontent.com/123756372/219032168-00ce1ca6-4f87-499e-ad11-ed4d27348c88.png">

**Comment by saharmor** [comment]
Thanks for reporting, I've just fixed the error. Please check and reopen if error persists.

**Comment by chemaomao** [comment]
Thanks for checking so fast! But the error persists on my side. 
<img width="1753" alt="Screenshot 2023-02-16 at 11 25 41" src="https://user-images.githubusercontent.com/123756372/219349351-b0e5d11e-063e-4a9c-82d2-690ea8d6d333.png">

**Comment by saharmor** [comment]
Can you past a screenshot of the `Run the backend web server` section of the notebook you're running?

**Comment by saharmor** [comment]
@chemaomao it should be fixed now. Can you please try again and report back?

**Comment by chemaomao** [comment]
Its running again, thank you!
<img width="1824" alt="Screenshot 2023-02-19 at 12 22 00" src="https://user-images.githubusercontent.com/123756372/219944820-a22ca6b8-8083-4094-9633-01720f0e76a8.png">
<img width="1082" alt="Screenshot 2023-02-19 at 12 21 44" src="https://user-images.githubusercontent.com/123756372/219944822-adbe6043-1c5d-4239-88d8-a2b07f8fc6de.png">

**Comment by saharmor** [comment]
Great, thanks for reporting!
