### ISSUE TITLE
No Cloudflare URL on Google Colab: Exception in thread Thread-12: / 1 required positional argument: 'metrics_port'

### ISSUE THREAD

**Issue by chemaomao** [saharmor/dalle-playground#132]
Error persists, after the issue was closed.
Cloudflare URL is not generated / reported on Google Colab.
Server still starts, but no front end access without the Cloudflare backend url.

> Exception in thread Thread-12:
> Traceback (most recent call last):
> File "", line 14, in start_cloudflared
> TypeError: _run_cloudflared() missing 1 required positional argument: 'metrics_port'
<img width="1753" alt="Screenshot 2023-02-16 at 11 25 41" src="https://user-images.githubusercontent.com/123756372/219357353-d6951e68-c0ec-4636-ace5-8db848bceb53.png">

**Comment by saharmor** [comment]
I've reopened the [previous issue](https://github.com/saharmor/dalle-playground/issues/131), let's resolve there instead of having a duplicate.
