### ISSUE TITLE
What is the backend URL if I run docker-compose?

### ISSUE THREAD

**Issue by CYLOL2019** [saharmor/dalle-playground#136]
I have successfully run the docker-compose and logged into the interface website. But what is the backend URL for me? 
Meanwhile, I have checked the port mapping for dalle-backend and dalle-interface. I found that there is no port mapping for the dalle-backend.
![1](https://github.com/saharmor/dalle-playground/assets/16497555/347a4a86-41a3-4200-a118-0c281ee57644)
![2](https://github.com/saharmor/dalle-playground/assets/16497555/cb319204-5000-45c8-a9c0-ec8ffdc25dd8)

**Comment by saharmor** [comment]
Did you try `http://localhost:3000/dalle-playground`?

**Comment by CYLOL2019** [comment]
> Did you try `http://localhost:3000/dalle-playground`?
Wow, thank you so much for personally answering my question! Isn't http://localhost:3000/ the address for the web frontend? I'm wondering if I also need to input the backend's URL. I've partially solved the previous issue - there was an incorrect Docker configuration. By adding the werkzeug==2.2.2 package to the requirements.txt file, I managed to get Docker running. 

However, I've encountered another problem now. I keep getting a 'connection error' message from the backend program.
![1](https://github.com/saharmor/dalle-playground/assets/16497555/e551b9c8-90c1-43d9-abe7-1f73bc04a38a)
![2](https://github.com/saharmor/dalle-playground/assets/16497555/8a5c1cd3-a57b-4713-ae07-25bdeb93d0ff)

**Comment by saharmor** [comment]
Have you tried Googling? https://saturncloud.io/blog/solving-huggingface-valueerror-connection-error-in-data-science-projects/#:~:text=The%20ValueError%3A%20Connection%20error%20typically,in%20the%20specified%20cached%20path.

https://github.com/huggingface/transformers/issues/10067

**Comment by CYLOL2019** [comment]
Thank you so much for your help. I had previously been addressing these issues step by step with Googling.

**Comment by saharmor** [comment]
Perfect, closing this issue.
