### ISSUE TITLE
 cannot import name 'url_quote' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by Alrefa3ee** [saharmor/dalle-playground#139]
windows 10 
cuda 12.1 
![Screenshot 2023-12-03 061217](https://github.com/saharmor/dalle-playground/assets/89798247/5a52784b-54d8-4b16-af71-1756d2789f48)

**Comment by loazeh** [comment]
did u find a solution ??

**Comment by saharmor** [comment]
@Alrefa3ee Please try to reproduce and reopen if the error persists.
