### ISSUE TITLE
When I implement app.py, it doesn't work

### ISSUE THREAD

**Issue by WOOJOOHAHM** [saharmor/dalle-playground#4]
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from dalle_mini.model import CustomFlaxBartForConditionalGeneration
ImportError: cannot import name 'CustomFlaxBartForConditionalGeneration' from 'dalle_mini.model' (/home/hahmwj/.local/lib/python3.8/site-packages/dalle_mini/model/__init__.py)

 It doesn't work with, how can I solve this error?

**Comment by ThatMykl** [comment]
I get the same error

**Comment by spcanales** [comment]
The same here:
`Traceback (most recent call last):
  File "dalle-playground/backend/app.py", line 9, in <module>
    from dalle_mini.model import CustomFlaxBartForConditionalGeneration
ImportError: cannot import name 'CustomFlaxBartForConditionalGeneration' from 'dalle_mini.model' `

**Comment by saharmor** [comment]
Hey everyone and thanks for flagging this. The code failed due to some changes in the underlaying DALL-E Mini package. I've fixed these errors and you should be able to run your local DALL-E playground.
Please reopen should the issue persist. Thanks!
