### ISSUE TITLE
Unable to get app.py to run (module not found error)?

### ISSUE THREAD

**Issue by leojamesstrong** [saharmor/dalle-playground#45]
I've been trying to run this via local development and, when running the "dalle_playground_backend" notebook, I haven't been able to get app.py to run backend URL output. I'm wondering if this is connected to an error `ModuleNotFoundError: No module named 'jaxlib'` or `ModuleNotFoundError: No module named 'flask' when` I try to run `python app.py 8080` or `python app.py 3000` in the terminal. Is there a step I'm missing? Thanks!

**Comment by saharmor** [comment]
Have you followed the readme instructions? https://github.com/saharmor/dalle-playground#local-development
Seems like you didn't run `pip install -r requirements.txt`

**Comment by saharmor** [comment]
Closing for now but feel free reopen if the error persists.
