### ISSUE TITLE
Colab running but playground web page does not connect with backend.

### ISSUE THREAD

**Issue by hemangjoshi37a** [saharmor/dalle-playground#48]
says : No running DALL-E server with this URL

**Comment by kyushuadamu** [comment]
@hemangjoshi37a 
Did you include http:// or https:// in the url?

related: #40

**Comment by ngmisl** [comment]
I get

`your url is: https://fifty-spoons-press-34-142-252-42.loca.lt/
tcmalloc: large alloc 10350092288 bytes == 0x7f177f550000 @  0x7f1b6cdad1e7 0x4a3940 0x5b438c 0x5ea94f 0x5939cb 0x594cd3 0x5d0ecb 0x59aeca 0x515655 0x549e0e 0x4bca8a 0x59c019 0x595ef6 0x5134a6 0x549e0e 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x515600 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f1b6c9aac87 0x5b621a
/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 6 leaked semaphores to clean up at shutdown
  len(cache))`

**Comment by real-jiakai** [comment]
You should be patient. I waited for nearly 5~10 minutes. Then this error disappeared.
This is my interface.
![image](https://user-images.githubusercontent.com/82650452/174050959-179d4312-7ad4-4d53-a339-4921cec74ddd.png)

**Comment by saharmor** [comment]
Closing for now. Feel free to reopen and provide further details if the error persists.

**Comment by hemangjoshi37a** [comment]
> @hemangjoshi37a Did you include http:// or https:// in the url?
> 
> related: #40

Yes I did include but I this as mentioned above I have to be more patient about loading it for like 5 to 10 minues. Obviusly I didnt waited that long in my case. 
[hjlabs.in](https://hjlabs.in)
