### ISSUE TITLE
Google Colab Free Error

### ISSUE THREAD

**Issue by arturobandissimo** [saharmor/dalle-playground#54]
Anyone else getting this error? 
Free version of colab.
Dalle "Mini" as option.
Project still runs but wondering if it's missing something.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
```

**Comment by VeXHarbinger** [comment]
I get that error as well but it still generates images for mini.

**Comment by saharmor** [comment]
This is being generated due to one of the dependencies (datascience) and shouldn't affect your ability to generate images. Feel free to reopen if this causes any downstream errors.
