### ISSUE TITLE
Invalid syntax in the backend web server

### ISSUE THREAD

**Issue by Erfie** [saharmor/dalle-playground#62]
Can't run the dalle in colab as the syntax is invalid.
`File ["<ipython-input-7-32c8736da626>"](https://localhost:8080/#), line 3
    app_port = 8000def app():
                     ^
SyntaxError: invalid syntax`

![image](https://user-images.githubusercontent.com/5338222/173609111-0ecc3c3a-7cbe-43e0-b5ee-ae9bf2b7091f.png)

**Comment by ericjlubbers** [comment]
Were you using this via Colab? I'm also getting invalid syntax but can't figure out what I need to do differently to avoid this error

```
File ["<ipython-input-5-32c8736da626>"](https://localhost:8080/#), line 3
    app_port = 8000def app():
                     ^
SyntaxError: invalid syntax
```

**Comment by merlinND** [comment]
Just add a new line break after `8000`:

```python
app_port = 8000
def app():
```
