### ISSUE TITLE
SyntaxError: invalid syntax - line 3, app_port = 8000def app():

### ISSUE THREAD

**Issue by skeddles** [saharmor/dalle-playground#63]
The colab worked a few days ago, but now gets an error when running the backend server.

![image](https://user-images.githubusercontent.com/2721332/173633976-b9fceb98-4740-4a5b-b7c2-43cbef4239cf.png)

**Comment by skeddles** [comment]
Seems to be from this commit earlier today

https://github.com/saharmor/dalle-playground/commit/c70679b5844126855bf1419367748c801f6b4051

**Comment by trekkie1701c** [comment]
Looks like it just needs a newline.

**Comment by TyraelElDruin** [comment]
I'm trying to build with docker and running into the syntax error. I added the newline in my local source code, but I'm wondering if docker pulls from that? I'm testing now.

**Comment by TyraelElDruin** [comment]
I think the dockerfile may need to be updated like this: `CMD python3 app.py --port 8080` - at least that's what worked for me.

**Comment by saharmor** [comment]
Thanks for surfacing this! Got fixed as part of https://github.com/saharmor/dalle-playground/commit/83c27cef066f4130fe98dac8d1c41aadbd372cb5

**Comment by skeddles** [comment]
Thank you @saharmor!
