### ISSUE TITLE
CORS 

### ISSUE THREAD

**Issue by akre54** [saharmor/dalle-playground#67]
Getting a frontend error:

```
Error querying DALL-E service. Check your backend server logs.
```

This is in the Chrome dev console:

```
Access to fetch at 'https://empty-oranges-juggle-*-*-*-222.loca.lt/dalle' from origin 'https://saharmor.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Backend service is showing 200. Either the server needs to send the header, or the frontend `fetch` call needs to be fixed. Right now it [sends `no-cors` as a header](https://github.com/saharmor/dalle-playground/blob/a7ffef51c466795be04b8a2c66c06831a2e8f4ce/interface/src/backend_api.js#L12) instead of as a root-level property.

**Comment by saharmor** [comment]
@akre54 How many images are you trying to generate and which model version (mini, mega)? This is most probably a timeout error where the backend takes >1 minute to generate images.

**Comment by akre54** [comment]
5, mega full.

Could the error message potentially be more helpful then? Also, regardless of timeout, the mode property lives on the root options object, rather than the headers.

**Comment by saharmor** [comment]
Good point. I've added a task to show a better error message upon the 1 min timeout.
Closing this issue for now as it isn't related to the CORS header.
