### ISSUE TITLE
Error using Docker: app.py: error: unrecognized arguments: 8080

### ISSUE THREAD

**Issue by palexpereira** [saharmor/dalle-playground#72]
Hello,
I'm getting this error after running docker compose up command:

Compiled with warnings.
dalle-interface    | 
dalle-interface    | ./src/TextPromptInput.js
dalle-interface    |   Line 1:17:  'useState' is defined but never used  no-unused-vars
dalle-interface    | 
dalle-interface    | ./src/BackendUrlInput.js
dalle-interface    |   Line 30:8:  React Hook useEffect has a missing dependency: 'onChange'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
dalle-interface    | 
dalle-interface    | ./src/LoadingSpinner.js
dalle-interface    |   Line 33:8:  React Hook useEffect has a missing dependency: 'textIdx'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
dalle-interface    | 
dalle-interface    | Search for the keywords to learn more about each warning.
dalle-interface    | To ignore, add // eslint-disable-next-line to the line before.
dalle-interface    | 
dalle-backend      | --> Starting DALL-E Server. This might take up to two minutes.
dalle-backend      | usage: app.py
dalle-backend      |        [-h]
dalle-backend      |        [--port PORT]
dalle-backend      |        [--model_version MODEL_VERSION]
dalle-backend      |        [--save_to_disk SAVE_TO_DISK]
dalle-backend      | app.py: error: unrecognized arguments: 8080
dalle-backend exited with code 2

after this it just repeats the dalle-backend error over and over again.
Changing the port number on the Dockerfile or the yaml file doesn't make a difference.

I have docker and nvidia container installed properly.
Running on Ubuntu 22.04
3090 RTX

Thanks!

**Comment by TyraelElDruin** [comment]
@palexpereira need to change backend docker file (last line) to `CMD python3 app.py --port 8080`

**Comment by TyraelElDruin** [comment]
See these issues: https://github.com/saharmor/dalle-playground/issues/63

https://github.com/saharmor/dalle-playground/pull/61

They're committing fixes soon.

**Comment by saharmor** [comment]
Fixed as part of [this commit](https://github.com/saharmor/dalle-playground/commit/d86d1816b60228bb6f9de460cc020c3aedae54d9). Feel free to reopen if error still persists.
