### ISSUE TITLE
`http://localhost:8080` does not pass isValidURL check

### ISSUE THREAD

**Issue by BBaoVanC** [saharmor/dalle-playground#86]
I tried running this locally with the included Docker Compose config, but the [regex in `utils.js`](https://github.com/saharmor/dalle-playground/blob/d86d1816b60228bb6f9de460cc020c3aedae54d9/interface/src/utils.js#L2-L7) doesn't consider `localhost` a valid domain.

Using `http://127.0.0.1:8080/` instead worked.

Test this on Regex101: https://regex101.com/r/Pu04zP/1

**Comment by saharmor** [comment]
Fix in https://github.com/saharmor/dalle-playground/commit/e7756b2ed79c6252121975d657783cc6a6c6878f
