### ISSUE TITLE
development mode generate images very slow

### ISSUE THREAD

**Issue by zhang-xiao** [saharmor/dalle-playground#9]
hi,

when I try this project, the images generate very slow in local development mode.

I am interested in the project, but have no much knowledge of it, while I run it on my laptop following your guide successfully.

so, I wonder if there is a way to speed images generating ?

thanks a lot.

**Comment by saharmor** [comment]
Hey! I'd suggest running the project in Google Colab using the notebook from this repo [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)].
I use Google Colab Pro which generates 5 images in ~20 seconds.
