### ISSUE TITLE
images output format changed

### ISSUE THREAD

**Issue by dcsan** [saharmor/dalle-playground#92]
just in case anyone else hit this.

my service that was pulling from dall-e mini model seems to now get images in jpeg format, and the response structure changed.

I guess this change?
https://github.com/saharmor/dalle-playground/commit/cad1753193ed15c06c6dddc076d0f5d4a04653a7

I'm using node server side to extract, so now extract these fields

```ts
    let images, parsed, format

    try {
        // @ts-ignore
        parsed = JsonBigint.parse(response)
        images = parsed.generatedImgs
        format = parsed.generatedImgsFormat // seems to switch between 'png' and 'jpg'
        if (!images) {
            clog.error('cannot parse images from response', { response, data: parsed })
            throw Error('cannot parse images from response')
        }
    } catch (error) {
        clog.error('expection on parsing dalle response', { error, response, data: parsed })
    }
```

**Comment by saharmor** [comment]
@dcsan that's correct, sorry for the breaking changes. I had to add an extra variable while the response was only a json-version of the`generatedImgs` list.
