### ISSUE TITLE
[WSL2 Ubuntu 20.04] No Backend URL generated, TF memory allocation errors on mini?

### ISSUE THREAD

**Issue by SC-004096** [saharmor/dalle-playground#99]
Attempting the manual setup
----
I run the following command to start this up: 
_python3 app.py --port 8080 --model_version mini_

![image](https://user-images.githubusercontent.com/45322153/175857668-c000068f-d624-486e-9be5-b08bd1510dd4.png)
I get a ton of Tensorflow errors for memory allocation, but my VRAM usage is only about 3GB/16GB at this point - with Mini, I had thought 16GB VRAM would be more than enough to run it?

When I go to the localhost page, I also just get an output of:
`{"success":true}`
And nothing else, so I'm not sure what I'm supposed to do here. I'm guessing I screwed it up somehow along the line, but I'm not quite sure where to figure out where the real problem is?

I do remember when I first set up WSL I was able to get some sort of backend URL generated (from an older commit), but I did not have CUDA setup or anything, so it had been defaulting to the CPU, but I couldn't tell you exactly what I had run to get to this point, or when it ended up breaking.

I know a few of the issues have a similar issue with the memory allocation as well, but I don't think I saw anything about the backend URL just... not appearing.

The Docker setup
-----
So after not knowing what to do, I tried the setup with Docker. So far with that, I get the frontend page that asks me for a URL, but when it starts the server, I never see any other messages, and no VRAM usage like with the manual way, nor any extra links? 
![image](https://user-images.githubusercontent.com/45322153/175857234-7c4577b2-4fcb-4ed0-a29d-1c4190cc58da.png)

I'm just really stuck and would appreciate some sort of step in the right direction, if anyone has had a similar issue (I guess this is probably more than one issue though), or knows I overlooked something.

**Comment by trekkie1701c** [comment]
In manual mode you have to have a second shell and cd into the interfaces directory, run npm install and then mpn start.  Then you'll have a frontend - like the one you saw in Docker - at localhost:3000.  From there you can put in the URL "http://localhost:8080" where it asks for a URL.

I believe this should be the same for the Docker version, just it only shows you the frontend having loaded.

**Comment by SC-004096** [comment]
Wow.

Alright well I'm a dingus. Thanks for the help, I was able to get it working, for some reason I guess I was fixated on having like, some sort of loca.lt link (or whatever the latest version link points to), and I don't even know why.

Thanks for the help.
